### ISSUE TITLE
PHP_CodeSniffer Support

### ISSUE THREAD

**Issue by szeck87** [Unibeautify/beautifier-php-codesniffer#1]
_From @muuvmuuv on June 20, 2018 12:4_

**Beautifier Details**
Name: PHP_CodeSniffer (phpcs)
Link to project/homepage: https://github.com/squizlabs/PHP_CodeSniffer

**If this is to update an existing beautifier, please describe what should be updated**
currently, in PHP just php-cs-fixer is supported, but phpcs also supports auto fixing with the `phpcbf ` command. It would be nice to support phpcs too

Languages Supported: PHP
How is it run (node, terminal, etc): PHP terminal with `phpcs <file> <options>`

_Copied from original issue: Unibeautify/unibeautify#110_

**Comment by szeck87** [comment]
_From @Glavin001 on June 20, 2018 14:45_

Thank you for creating this Issue, @muuvmuuv .

I've created https://github.com/Unibeautify/beautifier-php-codesniffer . Please feel free to submit a Pull Request there. I recommend following https://github.com/Unibeautify/beautifier-php-cs-fixer
Please let us know if you have any questions 😃 .

**Comment by Glavin001** [comment]
@szeck87 @muuvmuuv I'm going to work on this now to get an initial version out. 😃

**Comment by Glavin001** [comment]
Website: https://github.com/Unibeautify/website/pull/102
VSCode: https://github.com/Unibeautify/vscode/pull/56
