### ISSUE TITLE
VSCode prints abort format on save error

### ISSUE THREAD

**Issue by muuvmuuv** [Unibeautify/beautifier-php-codesniffer#20]
Today VSCode dev console printed an abort warning that it has aborted formatting on saving when using Unibeautify with `phpcs`. Could happen in other languages too but I have only noticed it on PHP_CodeSniffer yet.

![screenshot 2018-08-14 at 09 20 52](https://user-images.githubusercontent.com/11534760/44077405-dd3b0906-9fa3-11e8-80a3-8d7c16aa1c97.png)

Formatting with `Option+Shift+F` still works. Maybe a VSCode issue, but I wanted to submit it here first.

**Comment by Glavin001** [comment]
@muuvmuuv Could you provide some more details on how to reproduce this? Such as a code file, configuration file, etc.

**Comment by muuvmuuv** [comment]
I'm trying to save a file with autoformatting; this one: https://hastebin.com/rirecojuso.bash

Unibeautify cong: https://hastebin.com/egaveyedet.json
phpcs.xml: https://hastebin.com/uveturimux.xml

**Comment by Glavin001** [comment]
> Aborted format on save after 750ms

I think the beautification of your file is unavoidably slow 😢.

VSCode itself enforces the 750ms limit for `format on save`.
Other code formatters / beautifiers are experiencing this issue as well. 

We're falling into category 3 as described in https://github.com/Microsoft/vscode-go/issues/1419#issuecomment-355654879

> 3. Formatter takes more than 750ms
> Slow formatters are aborted by the format on save feature of VS Code as they can delay the save operation and cause perf issues.

From Unibeautify / beautifiers side, it looks like the only thing we could do is add log a message in the console when the beautification process is taking too long.

**Fortunately, it appears there is a configuration option for VSCode! 🎉** 
Check out `editor.formatOnSaveTimeout`: https://code.visualstudio.com/docs/getstarted/settings#_default-settings

```
  // Timeout in milliseconds after which the formatting that is run on file save is cancelled.
  "editor.formatOnSaveTimeout": 750,
```

Applicable code: 
- https://github.com/Microsoft/vscode/blob/ea7232e79119c3537945932006653ae252e9ee2b/src/vs/workbench/api/electron-browser/mainThreadSaveParticipant.ts#L216
- https://github.com/Microsoft/vscode/blob/1a0311ae4e303de98c2d60b2ca80928ad37878b4/src/vs/workbench/parts/files/electron-browser/files.contribution.ts#L333-L339

And the VSCode maintainers are collecting `editor.formatOnSaveTimeout` numbers so they can change the default value 👍. See https://github.com/Microsoft/vscode-go/issues/1613

**Comment by muuvmuuv** [comment]
That sounds great! We should add this in the documentation to inform others that came into the same problem.

**Comment by muuvmuuv** [comment]
It is working now! Another improvement would be a user message that says "VSCode's default formatOnSave timeout is to low for this file to be formatted, please increase it to a higher value to avoid timeout errors" and additionally a console log that prints the time Unibeautify has needed to format a file. @Glavin001

**Comment by Glavin001** [comment]
@muuvmuuv Would you be able to make a small PR to change https://github.com/Unibeautify/vscode#question-faq and add a note about this seeing error message and solution is to increase `editor.formatOnSaveTimeout`? 😃

**Comment by muuvmuuv** [comment]
@Glavin001 will PR soon. What do you think about creating summaries from the FAQ items to keep them small?
